# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :custom_lane do
    # add actions here: https://docs.fastlane.tools/actions
  end

  lane :beta do
    ensure_git_status_clean
    increment_build_number(build_number: number_of_commits)
    commit_version_bump
    add_git_tag
    push_to_git_remote
    match
    build_app(scheme: "Runner",
              workspace: "Runner.xcworkspace")
    changelog_from_git_commits(merge_commit_filtering: exclude_merges)
    upload_to_testflight
  end
end
